### ISSUE TITLE
Allow grid sizes to be lower than one unit.

### ISSUE THREAD

**Issue by Grocel** [LogicAndTrick/sledge#192]
I hope that you lower the minimum grid sizes for more accurate positioning and sizing. Since the compile tool can't handle micro brushes (brushes less then one unit long in one of their dimensions), the minimum size should still remain to one unit.

Many models and entities (especially in source) aren't exactly aligned to whole units, so it would make stuff a whole lot easier to handle when you enable this.

Also, this feature is that what I would understand with "Proper decimal precision for sub-grid geometry" as the homepage says.

**Comment by LogicAndTrick** [comment]
The latest release supports grid sizes down to 0.25.
