### ISSUE TITLE
"Steam Directory" does not populate "Steam Username" combo-box once set.

### ISSUE THREAD

**Issue by bigp** [LogicAndTrick/sledge#194]
I've tried setting this to my Steam directory, to the SteamApps subfolder, nothing populates the **Steam Username** dropdown list. **List Available Games** Also doesn't do anything.

I was under the impression I could auto-populate the **Game Configurations** tab if I could get these settings populated. I can't get anything to work without this first-time Game Configuration setup.

**Comment by LogicAndTrick** [comment]
The "Steam directory" setting has been removed, so this is no longer an issue.
