### ISSUE TITLE
Selecting brush vertexes in 3D view causes erratic movement

### ISSUE THREAD

**Issue by NukemD** [LogicAndTrick/sledge#195]
If you use the vertex tool on a brush and select any vertex point on a brush from the 3D view, moving it around in any viewport causes it to fly around at extreme speeds. The vertex will continue to move at high velocity away from the brush origin no matter which direction you try to move it.

The only way to recover from this problem is to back out of vertex edit mode and undo the changes to the brush.

**Comment by LogicAndTrick** [comment]
This issue was fixed in the latest release.
