### ISSUE TITLE
Cross-Platform UI Suggestion

### ISSUE THREAD

**Issue by ghost** [LogicAndTrick/sledge#212]
Just putting this out there: There's a free and open source framework that allows for the creation of a cross-platform UI. It's called ETO.Forms, and it has UI support for WinForms, GTK 2 & 3, MonoMac, etc. This would enable native(!) Linux and OS X support, which would be totally awesome. Would also allow me, and others, to dump Windows and just use OS X and Linux.

OpenTK ETO (https://github.com/picoe/Eto/issues/39)

Again, just putting this out there.

**Comment by tjhorner** [comment]
+1

**Comment by fdpierson** [comment]
I'll have to look into Eto and see what it provides. Being able to use native widgets through an abstraction is great, although being able to use them directly would allow you to even better match the look and feel of an operating system. Being able to create your own abstractions for forms would be ideal.

**Comment by JamesK89** [comment]
@NovaPikmin Thanks for the tip! Eto looks like what I've been looking for ever since wx.NET was abandoned.

**Comment by LogicAndTrick** [comment]
Closing as part of #238, see full comment on #217.
