### ISSUE TITLE
Current Sledge status

### ISSUE THREAD

**Issue by asd55** [LogicAndTrick/sledge#216]
sledge is dead? D:

**Comment by Ethaligan** [comment]
I hope not... :cry:

**Comment by JamesK89** [comment]
It appears the most recent commit was to the rendering-impl branch three months ago. I haven't been working on Sledge lately myself due to being busy to life commitments. I can try to reach out to LogicAndTrick and see what is going on.

**Comment by LogicAndTrick** [comment]
It's not dead, don't worry :)

However, I've been busy with other projects recently, so I haven't been working on it. Hopefully I will have time to start working on Sledge again in a few months.

I still stand by what's in the readme file:

> While progress is slow, I have every intention of continuing work on this project.

**Comment by Ethaligan** [comment]
Great, **thanks**! :smiley:

**Comment by Noiwex** [comment]
Do you have sorta roadmap or trello board?

**Comment by LogicAndTrick** [comment]
Not really, nothing official. Adding Source support is the target at the moment, though I plan to keep improving the Goldsource functionality while I do that.

I've almost finished a rewrite of the rendering engine (see branch [feature/rendering-impl](https://github.com/LogicAndTrick/sledge/tree/feature/rendering-impl)), which will add a bunch of features that are needed for rendering of certain Source features (displacements, blend textures, VTF shaders, animated textures and models, etc).

After that, the plan is to add Source features one at a time, making sure the it'll work on all engines. For example, displacements will work in Goldsource, and convert to tetrahedrons on compile. Instances in Goldsource and pre-ep2 Source will work in a similar way.

The main issues I want to focus on to start with are:

- #209 - Source game configurations
- #210 - Source textures
- #211 - Displacements

In the (very) long term I have grand plans for plugins, scripting, multi-user (networked) editing, and other unrealistic features :)

**Comment by r1sc** [comment]
+1 for plugin support!

**Comment by LogicAndTrick** [comment]
Closing in favour of #238 and #237
