### ISSUE TITLE
No solid entities found

### ISSUE THREAD

**Issue by DropMotion** [LogicAndTrick/sledge#222]
### Hi

I have this error when I want to open the settings for an entity
And in the `entity tools` the `entity type` is blank.

---

Like this 

![1](https://monosnap.com/file/3H5C1EMpqyRMGMrfqxMt3MnoSadm2Z.png)

and

![2](https://monosnap.com/file/GV8Z9YXzlX8o1uqZsMcXSD3CUkovny.png)

---

My HL2 settings 

---

![3](https://monosnap.com/file/KwDFHj7Q8076E8WLOZuLRL6HphxluK.png)

**Comment by LogicAndTrick** [comment]
You need to add the HL2 FGD file to the "Entities" tab in your game settings. I think you can find it somewhere in the `bin` folder of the game.

Sledge doesn't officially support Source games yet, so it's not going to work well.

**Comment by DropMotion** [comment]
Thanks ! It works :+1: 
But i don't now if i can fix that but entities don't have model.

![1](https://monosnap.com/file/oBv3knfJKEJIOngwvNTzW5RhifiprA.png)
