### ISSUE TITLE
Textures not rendering in 3D view

### ISSUE THREAD

**Issue by fnky** [LogicAndTrick/sledge#228]
I can't get the textures, applied to brushes, to render in 3D view. These are imported from WAD `halflife.wad`. They do render in preview as well as the texture browser.

<img width="549" alt="screen shot 2016-01-28 at 10 47 13" src="https://cloud.githubusercontent.com/assets/995050/12640876/ab72dbe8-c5ac-11e5-90aa-6e94165bea41.png">

I use the OpenGL 1.0 renderer and default settings.

**Comment by LogicAndTrick** [comment]
I'm assuming the textures are loading correctly in the texture browser and so on? Try disabling things in the renderer settings, and see if that helps. Try turning off texture filtering first, it's probably the most likely candidate. If it's still not working, you might be out of luck unfortunately. Sledge wasn't really designed to work on virtual machines.

![Screenshot](https://cloud.githubusercontent.com/assets/3071180/12641302/8f5e2aae-c5fa-11e5-9721-a68ae0c4f125.PNG)

**Comment by fnky** [comment]
I am currently setting up a new VM using VMWare instead to see if it will improve things, will post info soon :-)

**Comment by LogicAndTrick** [comment]
The new release is using DirectX11, so I'm closing this OpenGL-related issue.
