### ISSUE TITLE
Sven Coop 5 Support

### ISSUE THREAD

**Issue by NukemD** [LogicAndTrick/sledge#229]
Sven Coop 5 was released a bit over a week ago and one of the changes was drastically increasing the world size. Half-Life natively has a world size of 8192^3, but SC5 increased that to 262144^3.

Would it be possible for Sledge to have that increased world size? The SC5 development tools currently use a very hacked and bodged version of Hammer 3.5 that can't handle the new limits properly at all.

**Comment by LogicAndTrick** [comment]
262144? That's huge! Sledge can support custom map sizes but I didn't think they'd ever get that high. You can override the map size in the "Entities" tab of game configuration, but it only goes up to half that number. That's still a huge map size!

![Override Size Screenshot](https://cloud.githubusercontent.com/assets/3071180/12700271/ca1fd72a-c828-11e5-9e46-0449c56a57e3.PNG)


But if you want the full size and you don't mind using a custom FGD for Sledge, you can use the `@mapsize(-131072, 131072)` directive in your FGD (it's a Source feature, but Sledge supports it for all engines).

Here's an FGD that'll work in Sledge to give you the map size you want. Save it as `sven-sledge.fgd` in the same folder as the regular `sven-coop.fgd` file and only include `sven-sledge.fgd` in your game configuration.

```
@mapsize(-131072, 131072)
@include "sven-coop.fgd"
```

![Custom FGD Screenshot](https://cloud.githubusercontent.com/assets/3071180/12700300/cf0007be-c829-11e5-9dc7-57f52f87b3b0.PNG)

**Comment by NukemD** [comment]
It looks like that did the job, thanks.

Are you planning on releasing a new build with some of the fixes that you've made on the bug reports? The one on the sledge website is pretty old :/

**Comment by LogicAndTrick** [comment]
Yeah I've been busy in the past year and haven't had much of a chance to work on it. I plan to start on it again in a month or two so hopefully I can get a release out around then.

**Comment by NukemD** [comment]
Looking forward to it! Hammer was long in the tooth 10 years ago but it's really showing its age now.
