### ISSUE TITLE
UTF-8 encoding is not supported

### ISSUE THREAD

**Issue by goodDOS** [LogicAndTrick/sledge#241]
I used fgd containing Chinese, and garbled.

![qq 20170615160200](https://user-images.githubusercontent.com/16776856/27172408-c0c19be2-51e7-11e7-9884-a0212c3e1d7c.png)

**Comment by goodDOS** [comment]
I want to translate this software into Chinese.

**Comment by LogicAndTrick** [comment]
Thanks! Translations for the app will be supported in the next version. I will make sure that Unicode FGD works as well!

**Comment by goodDOS** [comment]
Thank you, great application! :smiley:

**Comment by LogicAndTrick** [comment]
Hi, I took a quick look at using Unicode in an FGD and it is working for me - it might be caused a combination of several things such as font and your system's default language. Can you provide some extra information please?

- Your Windows install language
- Your language for non-unicode programs (control panel -> region-> administrative)
- The text encoding of the FGD file you are using

For me, the settings were English / Japanese / UTF-8 and my test worked correctly. 

![image](https://user-images.githubusercontent.com/3071180/27258227-89c8dfe4-5438-11e7-8174-fff12991ba1e.png)

My first guess is that it's text encoding: Sledge requires FGD files to be UTF-8 compatible, and you may be using a different encoding that's not compatible. The encoding of your file is important, if it's not UTF-8 then you will need to re-encode it using a text editor. (e.g. in Notepad++, go to Encoding -> Convert to UTF-8)

This is what it looks like when I use the wrong encoding type:

![image](https://user-images.githubusercontent.com/3071180/27258266-da6751c8-5439-11e7-95f9-b601f3eac054.png)

**Comment by goodDOS** [comment]
Sorry, I made a mistake. :sob: 
Now no problem.

![qq 20170619141456](https://user-images.githubusercontent.com/16776856/27272336-4f4ca26e-54fc-11e7-92d6-97ab45de12a3.png)

**Comment by LogicAndTrick** [comment]
Great! I will close the issue then :)
