### ISSUE TITLE
Suggestion: Include The Alien Swarm's Hammer Maya integration and more

### ISSUE THREAD

**Issue by xXxToxicBlueDustxXx** [LogicAndTrick/sledge#244]
It would be interesting that the next sleg build includes an integration with maya and it would also be nice to have a theme selector and give it a style Qt

**Comment by LogicAndTrick** [comment]
Unfortunately I don't think either of these are likely:

- Maya is an (expensive) commercial application and I don't plan to purchase it or integrate with it. I'll add .OBJ exporting back into the beta version in the next few weeks, that allows at least a basic level of integration with most 3D applications.
- Windows forms doesn't easily support theming as it's designed to use the Windows theme.
