### ISSUE TITLE
unable to compile map

### ISSUE THREAD

**Issue by xana43** [LogicAndTrick/sledge#257]
I need help with this, I was trying to compile a map, but it keeps saying  "unable to find gameinfo.txt" i'm not sure how to fix this, because no game configuration option can seem to allow me to find the proper gameinfo.txt (Note: I have tried the gameinfo.txt of hl, hl2, and sfm, but it seems that sledge can't see them)

**Comment by LogicAndTrick** [comment]
Sledge doesn't support Source at the moment (only HL1), so you will need to use Hammer.
