### ISSUE TITLE
Sledge is not opening

### ISSUE THREAD

**Issue by IDEXV** [LogicAndTrick/sledge#263]
When i try to open the **Sledge Editor**, it shows in the processes but it's not open or in a tray. 
It just sit's in the process and nothing happens.

**Comment by Spectre200511** [comment]
I even tried running in compatibility mode, and as administrator.

**Comment by Spectre200511** [comment]
@LogicAndTrick

**Comment by IDEXV** [comment]
Yeah, it works now.
