### ISSUE TITLE
Latest build not works with my GPU

### ISSUE THREAD

**Issue by Karaulov** [LogicAndTrick/sledge#264]
NVIDIA GeForce 9500GT 256MB DirectX 10.

**Comment by Karaulov** [comment]
For fix need run dxcpl.exe,and add sledge directory. :(

**Comment by LogicAndTrick** [comment]
Hi, the latest build is using the Veldrid library, which is DirectX 11 only. Vulkan support can be added too but not older APIs like DirectX 10 or OpenGL.

I understand that this means the app won't work for some people and I'm sorry about that, but trying to cater for old hardware was seriously affecting my motivation to work on Sledge, so I am targeting modern platforms for my own sanity. DirectX 11 is almost 10 years old now and I think 10 years is long enough.

**Comment by Karaulov** [comment]
@LogicAndTrick 

It works if add sledge directory to dxcpl.exe

It's possible auto add with first run ?

![rfccdcl 1](https://user-images.githubusercontent.com/6445336/44977057-a1779700-af6f-11e8-8e12-81d595774ab6.png)

**Comment by LogicAndTrick** [comment]
Thanks, that sounds like a good work-around, I will mention it in the documentation.

It looks like those settings affect the computer globally (it could impact the settings if there are already programs in that list) so I don't think it's a good idea to perform it automatically, but maybe the installer can generate a registry file that the user can choose to run.

**Comment by LogicAndTrick** [comment]
Interesting, it looks like it would require a small change in the Veldrid library to support it. I might raise an issue and see if it's possible to add support.

**Comment by LogicAndTrick** [comment]
I think I managed to reduce the required version of DirectX to 10.0 [in the latest release](https://github.com/LogicAndTrick/sledge/releases/tag/2.0.6.0), can you try it out? It works for me if I force DX10 feature level in the control panel.

**Comment by Karaulov** [comment]
YES!
