### ISSUE TITLE
FGD Chinese character support?

### ISSUE THREAD

**Issue by goodman3** [LogicAndTrick/sledge#266]
If you load a FGD which contains Chinese description, it will show gibberish characters in smart mode. Which makes it unreadable. However the original Hammer supports Chinese FGD.

**Comment by TeamSpen210** [comment]
What character encoding are you using?

**Comment by LogicAndTrick** [comment]
You need to make sure your FGD is encoded in UTF-8. In Notepad++ or another editor, go Encoding -> Convert to UTF-8. 

![image](https://user-images.githubusercontent.com/3071180/45926246-f3ef1680-bf63-11e8-8cc3-be7a6bccfd80.png)

See issue #241, I still have that test key in my FGD and it's working fine.

![image](https://user-images.githubusercontent.com/3071180/45926252-1da83d80-bf64-11e8-965f-b5205db2704d.png)

**Comment by goodman3** [comment]
> You need to make sure your FGD is encoded in UTF-8. In Notepad++ or another editor, go Encoding -> Convert to UTF-8.
> 
> ![image](https://user-images.githubusercontent.com/3071180/45926246-f3ef1680-bf63-11e8-8cc3-be7a6bccfd80.png)
> 
> See issue #241, I still have that test key in my FGD and it's working fine.
> 
> ![image](https://user-images.githubusercontent.com/3071180/45926252-1da83d80-bf64-11e8-965f-b5205db2704d.png)

Thanks. It worked!
