### ISSUE TITLE
Fgd sprites not supported or this is bug?

### ISSUE THREAD

**Issue by Karaulov** [LogicAndTrick/sledge#269]
Fgd sprites not works or this is bug?

For example Info_player_start, etc...

Or how to download works fgd + sprites for cs 1.6 ?

**Comment by LogicAndTrick** [comment]
FGD sprites are supported, just make sure they're in the right folder.
If your FGD sprite paths are like `"sprites/something.spr"` then put your "sprites" folder in any of these locations:

- The same folder as the FGD (tick the setting in the environment options)
- The game or mod folder
- The editor folder in `C:\Program Files (x86)\Sledge Editor` (you'll already see there's two sprites in there)

**Comment by Karaulov** [comment]
Not works.

![gybaaep 1](https://user-images.githubusercontent.com/6445336/46680889-bd1b3080-cbf2-11e8-809c-c8c35aa30857.png)
![9fyhn3n 1](https://user-images.githubusercontent.com/6445336/46680894-c0aeb780-cbf2-11e8-8545-05251efeea14.png)
![njkiyey 1](https://user-images.githubusercontent.com/6445336/46680903-c99f8900-cbf2-11e8-804e-5118c2efb228.png)
![zrz7keo 1](https://user-images.githubusercontent.com/6445336/46680908-cc9a7980-cbf2-11e8-99c6-93ee57a98289.png)

**Comment by Karaulov** [comment]
@LogicAndTrick it can be fixed ? (i can see player sprite instead of green cube?)

**Comment by LogicAndTrick** [comment]
Alright, upload your FGD, sprites folder, and the contents of `%AppData%\Sledge` and I'll have a look.

**Comment by Karaulov** [comment]
[FGD.zip](https://github.com/LogicAndTrick/sledge/files/2470434/FGD.zip)
[Sledge.zip](https://github.com/LogicAndTrick/sledge/files/2470438/Sledge.zip)

**Comment by LogicAndTrick** [comment]
I published a new version, can you see if that fixes it?

**Comment by Karaulov** [comment]
Yes thanks !

**Comment by vmp32k** [comment]
I'm having this issue and figured out a problem which has something to do with the paths:

`@PointClass iconsprite("fgd/half-life/sprites/ambient_generic.spr") base(Targetname, MoveWith) = ambient_generic : "Universal Ambient"`

Shows a generic purple box.

`iconsprite("sprites/vhe/ambient_generic.spr")`

Show the proper speaker icon.
