### ISSUE TITLE
Copy/Paste not works ?

### ISSUE THREAD

**Issue by Karaulov** [LogicAndTrick/sledge#270]
I create object (for example cube), how to copy and paste (create duplicate) of this object ?
Ctrl+C/Ctrl+V not works ?

One time this works for info_player_start but then not works for any :(

**Comment by LogicAndTrick** [comment]
Ctrl+C/Ctrl+V will create a copy but it looks like there's a bug where it's not deselecting when you paste. Try Ctrl+C > Deselect all > Ctrl+V. It should work.

**Comment by Karaulov** [comment]
Possible object is not created in world after CTRL+V?
(After reopen Sledge, all objects are visible)

**Comment by LogicAndTrick** [comment]
It's created and added to the world, but both the copy and the original will be selected after you paste. If you deselect all and try to select again you'll see the copy. That's what it's doing when I try.

**Comment by Karaulov** [comment]
Yes this works, thanks. This can be fixed ? :)

**Comment by LogicAndTrick** [comment]
Yep, I'll fix it for the next version.

**Comment by Karaulov** [comment]
@LogicAndTrick i can't send error report in some cases (Error window is opened and closed in one-two seconds)

**Comment by Karaulov** [comment]
@LogicAndTrick  how to change angle while creating brush ? 

For example i need create tunnel, i select 'Pipe' brush, but this vertical, how to create horizontal 'Pipe'?

**Comment by Karaulov** [comment]
@LogicAndTrick , i got this 
![gsicvym 1](https://user-images.githubusercontent.com/6445336/46901970-9e07f180-cec5-11e8-9394-57ea61967f4a.png)
But i need this 
![oip3qf7 1](https://user-images.githubusercontent.com/6445336/46901974-a95b1d00-cec5-11e8-97d2-2d64426f8b0e.png)

**Comment by LogicAndTrick** [comment]
You need to rotate it after you create the brush. But people have asked for this feature before, it's on my list to be added at some point.

**Comment by Karaulov** [comment]
Thanks))  It will be more easy create objects))

Vertex manipulations can't be Undo/Redo ?

**Comment by LogicAndTrick** [comment]
It's the same as Hammer, you need to exit the VM tool to undo.
