### ISSUE TITLE
Carve is affecting objects that don't intersect

### ISSUE THREAD

**Issue by Karaulov** [LogicAndTrick/sledge#271]
I tried to make hole using cube brush, but got more holes than it should be :(

![kunnmmg 1](https://user-images.githubusercontent.com/6445336/46904620-e50adc80-ceef-11e8-9022-3514d5a170fa.png)
![kphryey 1](https://user-images.githubusercontent.com/6445336/46904624-efc57180-ceef-11e8-9800-2b6ba514e19d.png)

**Comment by Karaulov** [comment]
This is not the hole that I need :(

**Comment by LogicAndTrick** [comment]
Can you upload an example map so I can test it?

**Comment by Karaulov** [comment]
yes 
[de_vilry.zip](https://github.com/LogicAndTrick/sledge/files/2475464/de_vilry.zip)

**Comment by Karaulov** [comment]
@LogicAndTrick possible to add multiple carve ??

https://i.imgur.com/5FmzY9F.png

(Select multiple objects, and press carve)
