### ISSUE TITLE
#238 Follow Up Linux/Mac Help

### ISSUE THREAD

**Issue by communityus** [LogicAndTrick/sledge#308]
Wanted to follow up. I saw on #238 that was one of the milestones needed to allow portablitity to Linux/Mac is now done. So where can I start helping with the actual port to these platforms now?

https://github.com/LogicAndTrick/sledge/issues/238

**Comment by LogicAndTrick** [comment]
I'm not sure how much you read on that thread, but here's a quote from it:

> I've tried a few times before and it's far too difficult/unstable, so Linux/Mac support is not something I plan to spend any time on in the near future. If a stable, multi-platform UI framework for .NET with 3D support pops up at some point in the future I'll reconsider, but for now, there's no real option.

In terms of what needs to be done: The whole UI needs to be written in a multi-platform framework, and a stable .NET core UI platform doesn't really exist yet. Considering the significant work involved in a project like that, I believe it's not something that should be done in this repository.

It's much more reasonable for someone to create a new editor from scratch with platform compatibility in mind. It's possible that I will contribute to or perhaps even create an editor project like that, as I'm feeling like Sledge is currently at a dead end.
