### ISSUE TITLE
A couple of things I've implemented

### ISSUE THREAD

**Issue by lcarst** [LogicAndTrick/sledge#313]
I thought I'd post them here first instead of just spamming off pull requests.

Features:
- Mouse sensitivity setting.
- "Selection box selects by center handles only" setting.
- Setting to disable transform mode (translation/rotation/skewing) cycling when clicking on a selection.

Changes:
- Transform mode is reset to translation after deselecting something. Hammer behavior.  Added an option to re-enable that behavior.

Fixes:
- Visgroups not (de)serializing properly, causing them to be lost when the document is opened next time.
- Removed "TEXTURESIZEANDNAME" placeholder label in the texture application window since it's visible when there's no active texture.
- Issue #300 about illegal wads. They will remain in old documents.
- Issue #303 about texture application to multiple selected faces.

**Comment by LogicAndTrick** [comment]
They all sound good, feel free to create a PR when you want!

**Comment by lcarst** [comment]
There ya go :)
I forgot to mention that I've also changed dialog focus behavior. All dialogs lose focus on mouse leave, so I added regaining focus on mouse enter. It's not optimal, they shouldn't lose focus in the first place. The map viewports always grab it, I'm not sure how to permanently fix this
